[package]
name = "bridge-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.2", features = ["http2", "macros", "tracing"] }
dotenvy = "0.15.7"
jemallocator = "0.5.4"
jsonrpsee = { version = "0.20.3", features = ["http-client", "macros", "async-client"] }
reqwest = { version = "0.11.23", features = ["json", "brotli"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread", "parking_lot"] }
tower-http = { version = "0.5.0", features = ["trace", "compression-br"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
